apiVersion: batch.curator.openshift.io/v1
kind: Report
namespace: report-system
metadata:
  name: report-sample
spec:
  # Report displaying
  reportPeriod: Day
  namespace: koku-metrics-operator
  reportingEnd: "2021-10-03T12:00:00Z"  # prevents Reports targeting future time
  reportingStart: "2021-10-03T00:00:00Z"  # prevents Reports targeting future time
