kind: List
metadata: {}
apiVersion: v1
items:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: curator-s3-sync
    spec:
      lookupPolicy:
        local: true
      tags:
        - name: latest
          from:
            kind: DockerImage
            name: quay.io/operate-first/curator-s3-sync:latest
          importPolicy: {}
          referencePolicy:
            type: Local
  - apiVersion: v1
    kind: Service
    metadata:
      name: curator-reports
    spec:
      ports:
        - name: curator-reports
          nodePort: 0
          port: 5000
          protocol: TCP
          targetPort: 5000
      selector:
        name: curator-reports
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: curator-reports
    spec:
      replicas: 1
      selector:
        name: curator-reports
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            name: curator-reports
        spec:
          containers:
            - env:
                - name: POSTGRESQL_USER
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: v4
              image: "quay.io/operate-first/curator-s3-sync:latest"
              imagePullPolicy: IfNotPresent
              name: curator-reports
              envFrom:
                - secretRef:
                    name: api-credentials
              command:
                - sh
              args:
                ['-c', 'pip3 install flask; python3 /scripts/app.py']
              volumeMounts:
                - name: api-scripts
                  mountPath: /scripts
              ports:
                - containerPort: 5000
                  protocol: TCP
              resources:
                requests:
                  cpu: "1"
                  memory: 2Gi
                limits:
                  cpu: "1"
                  memory: 2Gi
          dnsPolicy: ClusterFirst
          restartPolicy: Always
